

export const SurveyTypes = {
        SAVE_SURVEY:'SAVE_SURVEY',
        EDIT_SURVEY: 'EDIT_SURVEY',
        LOAD_SURVEYS: 'LOAD_SURVEYS',
        FETCH_SURVEYS_START: 'FETCH_SURVEYS_START',
        FETCH_SURVEYS_SUCCESS: 'FETCH_SURVEYS_SUCCESS',
        FETCH_SURVEYS_FAILURE: 'FETCH_SURVEYS_FAILURE'
}