

export const SurveyTypes = {
        SAVE_SURVEY:'SAVE_SURVEY',
        EDIT_SURVEY: 'EDIT_SURVEY',
        ADD_SURVEY_QUESTION: 'ADD_SURVEY_QUESTION',
        DELETE_QUESTION_START: 'DELETE_QUESTION_START', 
        DELETE_QUESTION_SUCCESS: 'DELETE_QUESTION_SUCCESS',
        DELETE_QUESTION_FAILURE: 'DELETE_QUESTION_FAILURE',
        LOAD_SURVEYS: 'LOAD_SURVEYS',
        FETCH_SURVEYS_START: 'FETCH_SURVEYS_START',
        FETCH_SURVEYS_SUCCESS: 'FETCH_SURVEYS_SUCCESS',
        FETCH_SURVEYS_FAILURE: 'FETCH_SURVEYS_FAILURE'
}